export const reasonMessages: Record<string, { fi: string; en: string }> = {
  INVALID_DATE: { fi: 'Anna kelvollinen tarkastelupäivä.', en: 'Enter a valid assessment date.' },
  HISTORICAL_RULESET_NOT_AVAILABLE: { fi: 'Tälle päivälle ei ole historiallista sääntöpakettia.', en: 'No historical ruleset is available for this date.' },
  INVALID_CHARGE: { fi: 'Anna täytös numerona.', en: 'Enter the charge as a number.' },
  CHARGE_MUST_BE_POSITIVE: { fi: 'Täytöksen on oltava nollaa suurempi.', en: 'Charge must be greater than zero.' },
  REFRIGERANT_NOT_FOUND: { fi: 'Kylmäainetta ei löydy tästä tietoversiosta.', en: 'The refrigerant is not in this data version.' },
  VERIFIED_LEGAL_COMPOSITION_OR_GWP_REQUIRED: { fi: 'Laskentaan tarvittava varmennettu liiteluokka, seoskoostumus tai GWP puuttuu.', en: 'Verified annex classification, blend composition or GWP needed for this calculation is missing.' },
  NATURAL_OUTSIDE_FGAS_ODS_PERIODIC_RULE: { fi: 'Valittu kylmäaine ei kuulu näiden F-kaasu- tai otsoniasetusten määräaikaiseen vuototarkastussääntöön. Muut huolto- ja turvallisuusvelvoitteet voivat silti koskea laitetta.', en: 'This refrigerant is outside the periodic leak-check rules of these F-gas and ozone regulations. Other service and safety duties may still apply.' },
  MIXED_ODS_FGAS_RULE_UNVERIFIED: { fi: 'Otsoniaineen ja F-kaasun seokselle ei ole varmennettua sääntötulkintaa.', en: 'No verified rule interpretation is available for this ODS and F-gas mixture.' },
  NON_FGAS_BLEND_INTERPRETATION_UNVERIFIED: { fi: 'Tämän osittain sääntelemättömän seoksen tulkinta vaatii tarkistuksen.', en: 'This partly unregulated mixture needs an interpretation review.' },
  EQUIPMENT_OUTSIDE_SCOPE: { fi: 'Ilmoitettu laitetyyppi on tämän määräaikaisen vuototarkastussäännön ulkopuolella.', en: 'The selected equipment type is outside this periodic leak-check rule.' },
  SWITCHGEAR_INPUTS_UNAVAILABLE: { fi: 'Sähköisen kytkinlaitteen poikkeukset vaativat lisätietoja, joita tämä laskuri ei vielä kysy.', en: 'Switchgear exceptions need details this calculator does not yet collect.' },
  ODS_MOBILE_SCOPE_UNVERIFIED: { fi: 'Otsonisäännön soveltuminen tähän liikkuvaan laitteeseen vaatii tarkistuksen.', en: 'Application of the ozone rule to this mobile equipment needs review.' },
  MOBILE_TRANSITION_UNTIL_2027_03_12: { fi: 'Tämän liikkuvan laiteryhmän F-kaasun määräaikainen vuototarkastusvelvoite alkaa 12.3.2027.', en: 'The F-gas periodic leak-check duty for this mobile equipment group begins on 12 March 2027.' },
  MOBILE_SUBTYPE_REQUIRED: { fi: 'Liikkuvan laitteen tarkka tyyppi tarvitaan sääntöä varten.', en: 'The exact mobile equipment subtype is needed for the rule.' },
  ODS_EQUIPMENT_OUTSIDE_ARTICLE_21_3: { fi: 'Ilmoitettu laitetyyppi ei kuulu otsoniasetuksen 21 artiklan 3 kohdan tarkastusluetteloon.', en: 'The selected equipment type is not in the ozone regulation Article 21(3) inspection list.' },
  ODS_BELOW_3_KG: { fi: 'Otsoniainetta on alle 3 kg, joten 21 artiklan 3 kohdan määräaikainen kynnys ei täyty.', en: 'The ODS charge is below 3 kg, so the Article 21(3) periodic threshold is not met.' },
  ODS_LABELLED_HERMETIC_UNDER_6_KG: { fi: 'Merkitty ilmatiiviisti suljettu järjestelmä sisältää alle 6 kg otsoniainetta.', en: 'The labelled hermetic system contains less than 6 kg of ODS.' },
  ODS_PERIODIC_CHECK: { fi: 'Otsoniasetuksen määräaikainen vuototarkastus vaaditaan.', en: 'The ozone regulation requires periodic leak checks.' },
  ODS_DETECTOR_NO_INTERVAL_EXTENSION: { fi: 'Vuodonilmaisin ei pidennä otsoniasetuksen tarkastusväliä.', en: 'A detector does not extend the ozone-regulation inspection interval.' },
  FGAS_BELOW_ALL_THRESHOLDS: { fi: 'HFC:n CO₂e- ja HFO:n massakynnys jäävät molemmat alle tarkastusrajan.', en: 'Both the HFC CO₂e and HFO mass are below the inspection thresholds.' },
  FGAS_RESIDENTIAL_LABELLED_HERMETIC_UNDER_3_KG: { fi: 'Asuinrakennuksen merkitty ilmatiivis laite sisältää alle 3 kg F-kaasuja.', en: 'The labelled hermetic equipment in a residential building contains less than 3 kg of F-gas.' },
  MIXED_HERMETIC_OR_INTERPRETATION_UNVERIFIED: { fi: 'Seoksen HFC- ja HFO-haarat antavat eri tuloksen ilmatiiviin laitteen poikkeuksessa; asiantuntijatulkinta tarvitaan.', en: 'The HFC and HFO branches differ on the hermetic exemption; an expert interpretation is needed.' },
  FGAS_LABELLED_HERMETIC_EXEMPT: { fi: 'Merkitty ilmatiivis laite alittaa soveltuvan poikkeusrajan.', en: 'The labelled hermetic equipment is below the applicable exemption threshold.' },
  FGAS_ANNEX_I_PERIODIC_CHECK: { fi: 'Liitteen I aineiden CO₂e-määrä määrää tarkastusvälin.', en: 'The Annex I gases’ CO₂e quantity sets the inspection interval.' },
  FGAS_ANNEX_II_1_PERIODIC_CHECK: { fi: 'Liitteen II ryhmän 1 aineiden massa määrää tarkastusvälin.', en: 'The Annex II section 1 gases’ mass sets the inspection interval.' },
  LEAK_DETECTION_SYSTEM_REQUIRED: { fi: 'Tämän kiinteän laitteen suurelle täytökselle vaaditaan vuodonilmaisujärjestelmä.', en: 'This stationary equipment’s large charge requires a leak detection system.' },
  FIRE_PROTECTION_ALTERNATIVE_INSPECTION_REGIME: { fi: 'Sammutuslaitteiston hyväksytty ISO/EN-tarkastusjärjestelmä voi täyttää velvoitteen, kun väli toteutuu.', en: 'An accepted ISO/EN fire-protection inspection regime may fulfil the duty when it keeps the required interval.' },
  ORC_INSTALLATION_DATE_REQUIRED_FOR_DETECTOR: { fi: 'ORC-laitteen asennuspäivä tarvitaan vuodonilmaisimen velvoitteen arviointiin.', en: 'The ORC installation date is needed to assess detector obligations.' },
};
